### ISSUE TITLE
Could not find the poses_bounds_waymo.npy

### ISSUE THREAD

**Issue by Sudar278** [yifanlu0227/ChatSim#10]
Could not find the poses_bounds_waymo.npy while running 
python convert_metashape_to_waymo_script.py --datadir=/home/hp/ChatSim/data_utils/data/waymo_multi_view

![image](https://github.com/yifanlu0227/ChatSim/assets/119469584/df57cf2c-bee8-41e8-b608-870dfeebc7b0)

**Comment by yifanlu0227** [comment]
You need to run `python process_waymo_script.py --waymo_data_dir=../data/waymo_tfrecords/1.4.2 --nerf_data_dir=../data/waymo_multi_view` to get `poses_bounds_waymo.npy`, which stores camera extrinsics and intrinsics from original waymo dataset. This is an intermediate file and would not used at last.

A straightforward way is downloading our recalibrated pose files from [here](https://huggingface.co/datasets/yifanlu/waymo_recalibrated_poses/tree/main)

**Comment by yifanlu0227** [comment]
Oh, if you have downloaded the files from the huggingface and put them in the right position, you can just go next step. 

I previously updated the files in huggingface and all the required files are included now. So the **"and run the final step in the tutorial."** is not needed anymore. 

I updated README. Thank you for your correction.

**Comment by Sudar278** [comment]
Downloaded the data and stored in the mentioned location 

![image](https://github.com/yifanlu0227/ChatSim/assets/119469584/5e16cca6-62e2-4d04-98ad-3c2a8130b46d)

The following command is not creating the waymo_multi_view folder and seems the script is not running

![image](https://github.com/yifanlu0227/ChatSim/assets/119469584/463727c9-34cc-48ca-812d-eb7c247eca01)
