### ISSUE TITLE
About the 3D detection augmentation

### ISSUE THREAD

**Issue by LiuXuan66** [yifanlu0227/ChatSim#11]
I‘m new to Nerf. How do you obtain annotation information such as 3D boxes from simulation data that can be used for 3D detector training?

**Comment by yifanlu0227** [comment]
Hi, the 3D bounding box label is automatically generated with blender rendering if `save_cache` is enabled. You can find them in `ChatSim/results/cache/<EXP_NAME>/blender_output/<FRAME_ID>/label.yaml`
