### ISSUE TITLE
Why the car can't  appear in the camera area?

### ISSUE THREAD

**Issue by LiuXuan66** [yifanlu0227/ChatSim#17]
![图片](https://github.com/yifanlu0227/ChatSim/assets/61314087/28c410d7-17e7-4aa0-a050-6807d9a3bfd2)
The prompt is ‘add a black car on the front on the scene‘. I use my own data. I don't know where the problem is？It seems that my camera's posture is incorrect, it cannot face forward on the x-axis.The mcNerf training is right. Is there a fixed  code parameter written during the camera generation process？

**Comment by LiuXuan66** [comment]
#16 Perhaps I misunderstood the role of trans_mat。

**Comment by yifanlu0227** [comment]
#13 Maybe the same problem? You will have to align your world coordinate's origin with the ground.

**Comment by LiuXuan66** [comment]
> #13 Maybe the same problem? You will have to align your world coordinate's origin with the ground.

Does this mean that the ground is based on the vehicle coordinate system of the first frame? If that's the case, then I have already made the association because my ground feature coordinates are based on the vehicle coordinate system and do not need to be converted like Waymo.

**Comment by yifanlu0227** [comment]
<img width="1679" alt="Screenshot 2024-04-19 at 21 51 44" src="https://github.com/yifanlu0227/ChatSim/assets/45688237/08269ea6-e9a5-4782-90b3-9adab0cfba32">

Could you check it?

**Comment by LiuXuan66** [comment]
> <img alt="Screenshot 2024-04-19 at 21 51 44" width="1679" src="https://private-user-images.githubusercontent.com/45688237/323985117-08269ea6-e9a5-4782-90b3-9adab0cfba32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MzU0OTQsIm5iZiI6MTcxMzUzNTE5NCwicGF0aCI6Ii80NTY4ODIzNy8zMjM5ODUxMTctMDgyNjllYTYtZTlhNS00NzgyLTkwYjMtOWFkYWIwY2ZiYTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEzNTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNGNiNTUwZWVlNWJkZDQwYTgxNGQ4YmJkNWFmNDliOTgzZGY4YjY4ZmFmODA5MWJkNTc5MzhmNGNjNzFjOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DUubxMNkBzAn3jvWG23GMDBAlSLZDNIHgxuBWQBEngA">
> 
> Could you check it?

Yes, my own dataset is similar to Waymo, and its car coordinate system is also set at the bottom of the vehicle, with the coordinates facing the same direction as Waymo

**Comment by LiuXuan66** [comment]
You can see that the vehicle is generated in the correct world coordinate system, but the coordinates of the camera's blender are obviously incorrect, and its y-axis (triangular tip) is not pointing upwards.

**Comment by yifanlu0227** [comment]
https://github.com/yifanlu0227/ChatSim/blob/main/chatsim/foreground/Blender/utils/blender_utils/utils/visualize_pose.py

**Comment by yifanlu0227** [comment]
You need to run it on your PC with a display

**Comment by LiuXuan66** [comment]
Thanks a lot. I'll try it.

**Comment by LiuXuan66** [comment]
> You need to run it on your PC with a display

![图片](https://github.com/yifanlu0227/ChatSim/assets/61314087/e9eb43d8-f637-4060-8f35-44762d6bc371)
I have visualized the pose and I am not sure if the world coordinate system in the interface is FLU, so is this pose correct?

**Comment by yifanlu0227** [comment]
There is a segment indicating the up direction of your camera, so you can see how your camera is positioned (if you give the correct camera convention)
<img width="612" alt="Screenshot 2024-04-22 at 11 08 03" src="https://github.com/yifanlu0227/ChatSim/assets/45688237/9f39208b-f189-4730-a284-56b6f90d37af">

`FLU` is a camera convention, **not a world coordinate system property**. You should know your camera convention in your data format. But at least for now, it's not a normal visualization result. If your dataset is the same as waymo's, with xy plane determining the ground and +z pointing to the ground facing upwards, then probably your camera convention is incorrectly specified, so the cameras are facing crooked, but their trajectory looks reasonable.

![v2-77094ec63c1d68a0401cb0f7c10d8faa_r](https://github.com/yifanlu0227/ChatSim/assets/45688237/e54b9ca2-00c9-4409-bf1f-1955d05ce989)

**Comment by LiuXuan66** [comment]
Thank you very much for your answer. I will carefully examine the issue again

**Comment by LiuXuan66** [comment]
> #16  Finally, I obtained the correct pose by annotating trans_mat, and the vehicle can appear within the camera range.
