### ISSUE TITLE
Couldn't find this file: dataset/holicity_meta_info/selected_sample.json

### ISSUE THREAD

**Issue by LiuXuan66** [yifanlu0227/ChatSim#19]
I couldn't find this file: dataset/holicity_meta_info/selected_sample.json. Could you please provide it? Thank you very much

**Comment by yifanlu0227** [comment]
Sorry for the late reply. You can find the file [here](https://drive.google.com/drive/folders/1zbgwNBT-4Pvp-kgXXrOqpC0KhcwPyQ8J?usp=drive_link)

**Comment by LiuXuan66** [comment]
Thanks a lot!
