### ISSUE TITLE
waymo-1137-not-wide not work

### ISSUE THREAD

**Issue by chaoer** [yifanlu0227/ChatSim#27]
Hi,
Thanks for opensource your fancy work.

I tried the waymo-1137-not-wide.yaml for rendering efficiency, but result did not contain any object mentioned in the prompt. (even for the default prompt: "add a straight driving car in the scene" )

I notice that the rendering_mode is "render_hdr_shutter" in not-wide [yaml](https://github.com/yifanlu0227/ChatSim/blob/6a9bbec40e9ccecfff7edf270e713bed16329100/config/waymo-1137-not-wide.yaml#L33). However, there is no mode named "render_hdr_shutter" in [Exprunner file](https://github.com/yifanlu0227/ChatSim/blob/main/chatsim/background/mcnerf/src/ExpRunner.cpp). 

Is this the reason why no object appear in the final rendering result?

**Comment by yifanlu0227** [comment]
For some reason I'm just now getting around to replying to your issue, I'm very sorry. 

You're right, while doing the code refraction we probably copied this outdated file, making `render_hdr_shutter` mod lost. You need to add these line to `chatsim/background/mcnerf/src/ExpRunner.cpp` and recompile McNeRF, then it should work

```
  ...
  else if (mode == "render_hdr_shutter"){
    RenderPath(true, true, false);
  }
  else {
    std::cout << "Unknown mode: " << mode << std::endl;
  }
  
}

```

**Comment by yifanlu0227** [comment]
We would fix this bug and make the repo accelerated and more user-friendly in the next several commits. Then you can fetch the latest code. I will reply in the issue again once they are done

**Comment by chaoer** [comment]
> We would fix this bug and make the repo accelerated and more user-friendly in the next several commits. Then you can fetch the latest code. I will reply in the issue again once they are done

Thanks. 
Looking forward to your refactored code.

**Comment by chaoer** [comment]
BTW:

In current chatsim pipeline, we can obtain image in which a car occlude a tree if the car is before the tree. 
However, It seams that we can not get the tree occlude the car when the car is behand a tree.

Is there any possible that we render foreground object (e.g. car) with awareness of background depth (e.g. tree) in blender?

**Comment by yifanlu0227** [comment]
@chaoer Sorry for the late reply.

We leave the API for depth and occlusion detection (`['agents']['foreground_rendering_agent']['estimate_depth/depth_est']`), but we haven't found a robust detection estimation framework to calculate the background depth. Previously we used LiDAR projected depth + SAM to determine the region-wise depth, but that's not a very robust solution.

We notice [Metric3D](https://github.com/YvanYin/Metric3D) makes things easier and we will try to incorporate them into our codebase.

**Comment by chaoer** [comment]
@yifanlu0227 Thanks for your continually refactor and improvement of this fancy work. 
I will close this issue, and looking forward to you coming improvements.
