### ISSUE TITLE
Did you add the surrending light code?

### ISSUE THREAD

**Issue by StarsTesla** [yifanlu0227/ChatSim#34]
For NeRF and 3dGS

**Comment by yifanlu0227** [comment]
Yes, see the explanation [here](https://github.com/yifanlu0227/ChatSim?tab=readme-ov-file#config-file-explanation) and the [exemplar config](https://github.com/yifanlu0227/ChatSim/blob/main/config/waymo-1137-surrounding-light.yaml).

Note 1) we only provide the surrounding lighting for McNeRF 2) Currently surrounding lighting can be enabled when adding only one asset.

**Comment by StarsTesla** [comment]
Got it!
