### ISSUE TITLE
how render in multi-view image not in a wide-angle image? 

### ISSUE THREAD

**Issue by utc1205** [yifanlu0227/ChatSim#35]
Hi, I would like to thank for your great work. Recently I run the test script that renders cars in wide-angle image, we try to generate  simulation data. how render multi-view images like input images? Thank you in advance!

**Comment by vfishc** [comment]
Different rendering view depends on the intrinsics and extrinsics for rendering. You can change the intrinsics and extrinsics as the parameters you need for rendering. For instance, if you do not want wide-angle, which means the intrinsics should be changed as the original version, you can change it by modifying the code in chatsim/scene.py or set the is_wide_angle parameter in config as false. If you want to get the multi-view images, you should change the extrinsics during rendering process, unfortunately we do not offer direct api or config for it, but you can change the scene.current_extrinsics in chatsim/scene.py as other views by modifying the code. scene.nerf_motion_extrinsics is the loaded processed extrinsics, and be arranged as front_time0, frontleft_time0, frontright_time0, front_time1...... You can read the scene.nerf_motion_extrinsics to get the extrinsics to meet your requirement.

**Comment by utc1205** [comment]
thanks again !
