### ISSUE TITLE
FileNotFoundError: No such file:

### ISSUE THREAD

**Issue by LFerris123** [yifanlu0227/ChatSim#39]
When I try to test the simulation with the command `python main.py -y config/waymo-1137.yaml -p "Add a Benz G in front of me, driving away fast."`, I encounter the following error. I have already trained McNeRF, and I cannot find the target image file in the file path of this error. How should I resolve this issue? How should the image be generated?
![image](https://github.com/yifanlu0227/ChatSim/assets/85951430/762f9c8e-a547-412a-b46a-3fb3aa8e6b9c)

**Comment by yifanlu0227** [comment]
Hi! Do you have anything in `/home/lferris/ChatSim/chatsim/background/mcnerf/exp/segment-11379226583756500423_6230_810_6250_810_with_camera_labels/exp_coeff_0.3/wide_angle_novel_images/`? 

I just run the command in my machine but it does not raise a error?

**Comment by yifanlu0227** [comment]
Its logic goes like this.

You do not have a initial image in the `data/waymo_multi_view/${SCENE_NAME}` folder, so it will first call the McNeRF to generate one. 

The McNeRF is an external C++ program and it will save the rendered image to the disk (`/home/lferris/ChatSim/chatsim/background/mcnerf/exp/segment-11379226583756500423_6230_810_6250_810_with_camera_labels/exp_coeff_0.3/wide_angle_novel_images/50000_000.png` in your case). 

Then ChatSim would read the images and store them in the memory:

```
# chatsim/agents/background_rendering_agent.py
# line92- 93
            novel_image = imageio.imread(os.path.join(self.nerf_novel_view_dir, '50000_000.png'))[:, :scene.width]  #wide angle
            scene.current_images = [novel_image] * scene.frames
```


According to your information, the McNeRF can do the rendering, but it's not clear if it saves any images. If it saves, ChatSim should be able to read the rendered result from that path.

**Comment by LFerris123** [comment]
Thank you for your reply! I have checked the path '/home/lferris/ChatSim/chatsim/background/mcnerf/exp/segment-11379226583756500423_6230_810_6250_810_with_camera_labels/exp_coeff_0.3/wide_angle_novel_images/' and found an image named 25000_000.png. There was no error message indicating a missing image named 50000_000.png. Could it be that there was an error in accessing the image name? The style of the image is shown as follows:
<img width="896" alt="image" src="https://github.com/yifanlu0227/ChatSim/assets/85951430/ad695843-bbd2-46a2-8c54-ddbadde893b0">

**Comment by LFerris123** [comment]
Thank you for the reply! I have checked the path “/home/lferris/ChatSim/chatsim/background/mcnerf/exp/segment-11379226583756500423_6230_810_6250_810_with_camera_labels/exp_coeff_0.3/wide_angle_novel_images/” and found an image named 25000_000.png. There is no image named 50000_000.png as the error message suggested might be missing. Could it be that there was an error in the name of the image being accessed? The style of the image is as shown in the following picture:
![image](https://github.com/yifanlu0227/ChatSim/assets/85951430/4b5bfe96-7c4b-4ab5-b88f-0f187ef89f85)

**Comment by LFerris123** [comment]
![image](https://github.com/yifanlu0227/ChatSim/assets/85951430/dd31eb34-13e5-474f-8824-59bed3447d4d)

**Comment by yifanlu0227** [comment]
It is likely that you terminate the training in the middle. 50000 is the maximum iteration number we set. If you go to the checkpoint folder, you probably have the 00025000 only.

```
$ ls /home/yfl/workspace/ChatSim/chatsim/background/mcnerf/exp/segment-11379226583756500423_6230_810_6250_810_with_camera_labels/exp_coeff_0.3/checkpoints
>>>
00025000  00050000  latest
```

**Comment by LFerris123** [comment]
Okay, thanks for the response. The ultimate issue should be that I stopped the training midway.
![image](https://github.com/yifanlu0227/ChatSim/assets/85951430/a492dd45-e067-44e9-82c2-9250f8da8bd3)
