### ISSUE TITLE
data augmentation for different weather

### ISSUE THREAD

**Issue by utc1205** [yifanlu0227/ChatSim#42]
If we want to add weather simulation into chatsim, such as rainy days, how would you suggest we do this? Thank you in advance.

**Comment by yifanlu0227** [comment]
That's a good research question, and I guess @ZiWang1105 has many comment on it.

I would suggest you to refer more to Shenlong Wang's paper, such as [ClimateNeRF](https://climatenerf.github.io/), those guys explore a lot in the field of inverse rendering and weather simulation.

**Comment by ZiWang1105** [comment]
Hi, there are a couple of ways to achieve this in the image space. 

**Physics based**:
Foggy days: (https://www.ri.cmu.edu/pub_files/pub4/narasimhan_srinivasa_g_2003_4/narasimhan_srinivasa_g_2003_4.pdf) uses  atmospheric scattering model to add fog on image.
Rainy days: (https://team.inria.fr/rits/computer-vision/weather-augment/) uses particle simulator to add rain drops.

**Diffusion based**:
(https://github.com/GaParmar/img2img-turbo) You can customize your source and target domain of image translation and then train your own Diffusion model to convert a clear image to a image in another weather. 

You can also check ClimateNeRF, which adds weather conditions in NeRF space.

Thanks!

**Comment by utc1205** [comment]
Thank you for your suggestions, which give me a lot of inspiration. I appreciate it once again.
