### ISSUE TITLE
Simulation 3dgs training problem

### ISSUE THREAD

**Issue by Jumponthemoon** [yifanlu0227/ChatSim#43]
Hi,

I successfully trained the scene with 3dgs but encountered problem when simulation shown below:
![image](https://github.com/user-attachments/assets/7c7fc20b-9546-42cb-bac6-977309d23c11)

It looks like rendering works but the results are not saved in cache? And i found the 'blender_output' folder is empty. If you have any idea how to fix it?

Thanks!

**Comment by Jumponthemoon** [comment]
Btw, I've set 'save_cache' to be true.

**Comment by yifanlu0227** [comment]
Probably it is due to OOM, reduce `multi_process_num` in the yaml file. You can also check the log files under `result/cache/`

**Comment by Jumponthemoon** [comment]
> Probably it is due to OOM, reduce `multi_process_num` in the yaml file. You can also check the log files under `result/cache/`

Thanks for the quick response. I tried that and set it to be 1 but not working. The logs files under 'results/cache' is empty as well. I guess it might be due to the wrong installation of Blender. I will try to re-install it.

**Comment by Jumponthemoon** [comment]
> > Probably it is due to OOM, reduce `multi_process_num` in the yaml file. You can also check the log files under `result/cache/`
> 
> Thanks for the quick response. I tried that and set it to be 1 but not working. The logs files under 'results/cache' is empty as well. I guess it might be due to the wrong installation of Blender. I will try to re-install it.

I tried re-install the project on another machine. It works now. Maybe some installation step missing or run in the wrong place.
