### ISSUE TITLE
TypeError: 'numpy._DTypeMeta' object is not subscriptable

### ISSUE THREAD

**Issue by wmkai** [yifanlu0227/ChatSim#46]
when I was running `python process_waymo_script.py --waymo_data_dir=../data/waymo_tfrecords/1.4.2 --nerf_data_dir=../data/waymo_multi_view`, it shows 

![image](https://github.com/user-attachments/assets/3d228b66-76d2-4acd-8492-3accfb276816)

**Comment by yifanlu0227** [comment]
what is your numpy version? Try `pip install numpy<2.0.0` if your current version is 2.0

**Comment by wmkai** [comment]
> what is your numpy version? Try `pip install numpy<2.0.0` if your current version is 2.0

Thank you, it works for me. But when I try to run `bash train-1137.sh`, it shows
![image](https://github.com/user-attachments/assets/0a874911-dd3b-43c8-a480-d6c2df1a1db8)
I'm new to this area. I have 8 V100-32G GPUs and 320G memory. Do you have any idea to fix this problem?
